apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: svc1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: svc1
        image: darmawan/k8scom:v1.0.5
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: URL
            value: "http://svc2.default.svc.cluster.local/"
        command: ["node", "./svc1.js"]