apiVersion: v1
kind: Service
metadata:
  name: svc2
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: svc2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
      - name: svc2
        image: darmawan/k8scom:v1.0.5
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001
        env:
          - name: URL
            value: "http://svc1.default.svc.cluster.local/"
        command: ["node", "./svc2.js"]