apiVersion: v1
kind: Pod
metadata:
  name: svc1
spec:
  containers:
    - name: svc1
      image: darmawan/k8scom:v1.0.5
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: URL
          value: "http://localhost:3001/"
      command: ["node", "./svc1.js"]
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
      