apiVersion: v1
kind: Pod
metadata:
  name: svc2
spec:
  containers:
    - name: svc2
      image: darmawan/k8scom:v1.0.5
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3001
      env:
        - name: URL
          value: "http://localhost:3000/"
      command: ["node", "./svc2.js"]
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
      